#JSTF Configuration
browser: "chrome" #chrome, firefox.   remote driver & other browsers are coming soon.
is_headless_browser: "false"
reuse_browser: "false"
#browserHub=http://browserstack:4444/wd/hub

#mockproxy settings
is_mock_proxy_enabled: "true"
is_cors_enabled: "true" #only works when mock proxy enabled

#zap settings
is_zap_enabled: "false"
zap_server: 127.0.0.1:6666
zap_app_path: "" #ZAP zipped binary, or start script file.
zap_report_path: "target/ZAPReport.html"
zap_log_file: "target/jstflogs/zap.log"

#proxy settings
is_proxy_enabled: "false"
proxy_addr: 10.10.10.10:8080
#proxy_bypass: 10.*, 127.0.0.1

#Selenium settings
element_timeout: "30"
assertion_timeout: "3"
element_retrytimes: "10"
default_window_size: "" #1024*768, default is max window


#Accessibility(AXE) settings
axe_report_level: critical #critical, serious, moderate, all
axe_rules: all  #wcag2a, wcag2aa, wcag412,section508,section508.22.a, all