#JSTF Configuration
browser: "chrome"
is_headless_browser: "false"
reuse_browser: "false"
#browserHub=http://selenium-grid.master.dev.a1028-01.ams02.nonp.qcpaws.qantas.com.au:4444/wd/hub

is_mock_proxy_enabled: "false"
is_zap_enabled: "false"
zap_server: 127.0.0.1:6666

isProxyEnabled: "false"
proxyAddress: proxy.qcpaws.qantas.com.au:3128
proxyBypass: 10.*, *.qcpaws.qantas.com.au, www-staging.qantas.com, 127.0.0.1

#Corporrate Proxy Setup
is_proxy_enabled: "false" #true, false
proxy_addr: "proxy.qcpaws.qantas.com.au:3128"
proxy_bypass: "10.*, *.qcpaws.qantas.com.au, www-staging.qantas.com, 127.0.0.1"

#Selenium settings
element_timeout: "30"
assertion_timeout: "3"
element_retrytimes: "5"